export const LOCATION_CHANGE = 'LOCATION_CHANGE';

export const SAVE_AI_RESPONSE = 'SAVE_AI_RESPONSE';
export const SAVE_AI_ERROR = 'SAVE_AI_ERROR';
export const SEND_USER_INPUT = 'SEND_USER_INPUT';

export const SAVE_ARTICLES = 'SAVE_ARTICLES';
export const SAVE_HEADLINES = 'SAVE_HEADLINES';
export const SAVE_SOURCES = 'SAVE_SOURCES';
